baseURL = 'https://kcurde.com/'
languageCode = 'en-us'
title = "Klaire's Blog"
theme = 'archie'
copyright = '@ Klaire Curde'
paginate = 10

pygmentsstyle = "monokai"
pygmentscodefences = true


[params]
    favicon = "/coffee-cup-outline.ico"
    mode="toggle"
    subtitle="Hi I'm Klaire, and I'm a Software/DevOps Engineer that is undeniably addicted to coffee. I dump a lot of text here, enjoy your stay and use the content at your own risk!"


# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/klauscurde"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/klaire-curde/"

[[params.social]]
name = "CSH"
icon = "hard-drive"
url = "https://csh.rit.edu"


# Main Menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 4

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 5

[[menu.main]]
name = "Abyss"
url = "/abyss"
weight = 6
contentDir = "content/abyss"

[[menu.main]]
name = "Coffee"
url = "/coffee"
weight = 7


# Taxonomies
[taxonomies]
coffee = 'coffees'
